"""Synthetic reconciliation dataset generator.

    python scripts/generate_data.py --records 100000 --out data/demo

Produces three internally-consistent CSVs -- orders, settlements, bank
statement -- with a realistic mix of clean matches and seeded defects.  The
scenario mix is declared once in ``SCENARIOS`` and every row is generated by
the same arithmetic the engine reverses, so the expected outcome of each
scenario is knowable in advance (the tests rely on this).

Deliberately included:

* a genuinely **unresolved** bucket -- records whose variance no source record
  explains, so the UI can demonstrate graceful failure rather than a
  suspiciously perfect 100%;
* a few malformed cells (``"₹1,000"``, blank amounts, a bad date) so the
  validation layer has something to report on a real file.

Rows are streamed to disk with ``csv.writer``, so generating a million records
costs a few hundred MB of disk and almost no RAM.
"""

from __future__ import annotations

import argparse
import csv
import random
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.money import to_major  # noqa: E402

METHODS = ("UPI", "Card", "Netbanking", "Wallet")
BANKS = ("HDFC", "ICICI", "AXIS", "SBIN", "KKBK")

#: Razorpay-shaped economics: ~2% platform fee, 18% GST on the fee.
FEE_RATE = 0.02
GST_RATE = 0.18


@dataclass(frozen=True)
class Scenario:
    name: str
    weight: float
    description: str


#: Weights are proportions, not counts -- the mix holds at any --records value.
SCENARIOS: tuple[Scenario, ...] = (
    Scenario("clean", 0.900, "Fee and tax declared and correctly applied"),
    Scenario("partial", 0.030, "Bank credited less than the settlement states"),
    Scenario("refund", 0.025, "Refund applied on one side only"),
    Scenario("fee_tax", 0.015, "Fee/tax deducted twice"),
    Scenario("rounding", 0.015, "Sub-rupee rounding residual"),
    Scenario("missing_settlement", 0.008, "Order never settled -> UNRESOLVED"),
    Scenario("duplicate_settlement", 0.007,
             "Two settlement rows for one payment -> UNRESOLVED (ambiguous totals)"),
)


def paise(rupees: float) -> int:
    return int(round(rupees * 100))


def pick(rng: random.Random) -> Scenario:
    roll = rng.random()
    cumulative = 0.0
    for scenario in SCENARIOS:
        cumulative += scenario.weight
        if roll <= cumulative:
            return scenario
    return SCENARIOS[0]


def generate(
    records: int,
    out_dir: Path,
    *,
    seed: int = 42,
    days: int = 14,
    dirty_rows: int = 6,
) -> dict[str, Path]:
    rng = random.Random(seed)
    out_dir.mkdir(parents=True, exist_ok=True)
    orders_path = out_dir / "orders.csv"
    settlements_path = out_dir / "settlements.csv"
    bank_path = out_dir / "bank_statement.csv"

    start = datetime.now().replace(hour=9, minute=0, second=0, microsecond=0) - timedelta(days=days)
    counts: dict[str, int] = {s.name: 0 for s in SCENARIOS}
    #: Rows deliberately made malformed, to exercise validation on a real file.
    dirty_at = set(rng.sample(range(records), min(dirty_rows, records))) if records else set()

    with (
        orders_path.open("w", newline="", encoding="utf-8") as of,
        settlements_path.open("w", newline="", encoding="utf-8") as sf,
        bank_path.open("w", newline="", encoding="utf-8") as bf,
    ):
        orders = csv.writer(of)
        settlements = csv.writer(sf)
        bank = csv.writer(bf)

        orders.writerow(
            ["order_id", "payment_id", "order_amount", "currency", "order_date",
             "status", "payment_method"]
        )
        settlements.writerow(
            ["settlement_id", "payment_id", "gross_amount", "fee", "tax",
             "refund_amount", "settlement_amount", "currency", "settlement_date",
             "utr", "status"]
        )
        bank.writerow(
            ["bank_transaction_id", "settlement_id", "utr", "credit_amount",
             "currency", "value_date", "narration"]
        )

        for i in range(records):
            scenario = pick(rng)
            counts[scenario.name] += 1

            order_id = f"O-{100000 + i}"
            payment_id = f"pay_{i:09d}"
            settlement_id = f"setl_{i:09d}"
            utr = f"{rng.choice(BANKS)}{rng.randint(10**9, 10**10 - 1)}"

            gross = paise(rng.choice([499, 899, 1250, 1999, 2000, 3499, 4999, 7500, 12000])
                          + rng.randint(0, 99) / 100)
            fee = int(round(gross * FEE_RATE))
            tax = int(round(fee * GST_RATE))
            refund = 0
            captured = start + timedelta(
                days=rng.randint(0, days - 1), hours=rng.randint(0, 10),
                minutes=rng.randint(0, 59),
            )
            settled_at = captured + timedelta(days=2)

            if scenario.name == "refund":
                refund = paise(rng.choice([100, 250, 500]))

            # Net is always computed the same way; scenarios then perturb one
            # side of the reconciliation, exactly as a real defect would.
            net = gross - fee - tax - refund
            credit: int | None = net
            emit_settlement = True

            if scenario.name == "partial":
                credit = net - paise(rng.choice([150, 250, 400, 750]))
            elif scenario.name == "refund":
                credit = net - refund          # refund taken twice
            elif scenario.name == "fee_tax":
                credit = net - (fee + tax)     # fee+tax deducted twice
            elif scenario.name == "rounding":
                credit = net - rng.randint(1, 60)
            elif scenario.name == "missing_settlement":
                emit_settlement = False
                credit = None

            amount_cell = f"{to_major(gross)}"
            date_cell = captured.strftime("%Y-%m-%d %H:%M:%S")
            if i in dirty_at:
                # One of: a currency symbol, an empty amount, or a bad date.
                flavour = i % 3
                if flavour == 0:
                    amount_cell = f"₹{to_major(gross):,}"
                elif flavour == 1:
                    amount_cell = ""
                else:
                    date_cell = "31/02/2026"

            orders.writerow(
                [order_id, payment_id, amount_cell, "INR", date_cell,
                 "captured", rng.choice(METHODS)]
            )

            if emit_settlement:
                settlements.writerow(
                    [settlement_id, payment_id, to_major(gross), to_major(fee),
                     to_major(tax), to_major(refund), to_major(net), "INR",
                     settled_at.strftime("%Y-%m-%d"), utr, "processed"]
                )
            if scenario.name == "duplicate_settlement":
                # A second row for the same payment. The engine cannot know
                # whether this is a split payout or a duplicated export, so it
                # must refuse to guess -- this is the graceful-failure case.
                settlements.writerow(
                    [f"{settlement_id}_b", payment_id, to_major(gross), to_major(fee),
                     to_major(tax), to_major(refund), to_major(net), "INR",
                     settled_at.strftime("%Y-%m-%d"), f"{utr}B", "processed"]
                )
            if credit is not None:
                bank.writerow(
                    [f"bnk_{i:09d}", settlement_id, utr, to_major(credit), "INR",
                     settled_at.strftime("%Y-%m-%d"),
                     f"NEFT CR RAZORPAY {utr}"]
                )

        # One orphan settlement: money moved with no order behind it. Always
        # present, so the demo has a real "unexplained credit" to show.
        if records:
            orphan_utr = f"{rng.choice(BANKS)}{rng.randint(10**9, 10**10 - 1)}"
            settlements.writerow(
                ["setl_orphan_001", "pay_orphan_001", to_major(paise(5000)),
                 to_major(paise(100)), to_major(paise(18)), "0",
                 to_major(paise(4882)), "INR",
                 (start + timedelta(days=days - 1)).strftime("%Y-%m-%d"),
                 orphan_utr, "processed"]
            )
            bank.writerow(
                ["bnk_orphan_001", "setl_orphan_001", orphan_utr,
                 to_major(paise(4882)), "INR",
                 (start + timedelta(days=days - 1)).strftime("%Y-%m-%d"),
                 f"NEFT CR RAZORPAY {orphan_utr}"]
            )

    return {
        "orders": orders_path,
        "settlements": settlements_path,
        "bank": bank_path,
        "_counts": counts,  # type: ignore[dict-item]
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic reconciliation datasets."
    )
    parser.add_argument("--records", type=int, default=100,
                        help="number of orders to generate (default 100)")
    parser.add_argument("--out", type=Path, default=Path("data/demo"),
                        help="output directory (default data/demo)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--days", type=int, default=14,
                        help="spread orders over this many days")
    parser.add_argument("--dirty", type=int, default=6,
                        help="how many rows to deliberately malform")
    args = parser.parse_args()

    result = generate(
        args.records, args.out, seed=args.seed, days=args.days, dirty_rows=args.dirty
    )
    counts = result.pop("_counts")

    print(f"Generated {args.records:,} records into {args.out}/")
    for name, path in result.items():
        size = path.stat().st_size
        print(f"  {name:<12} {path.name:<22} {size / 1024:>10,.1f} KB")
    print("\nScenario mix:")
    for scenario in SCENARIOS:
        n = counts[scenario.name]
        share = n / args.records * 100 if args.records else 0
        print(f"  {scenario.name:<20} {n:>8,}  {share:>5.1f}%  {scenario.description}")
    print(f"  {'orphan_settlement':<20} {1:>8,}         Settlement with no matching order")
    print(f"  {'malformed_rows':<20} {min(args.dirty, args.records):>8,}"
          f"         Rejected by validation with a row-level reason")


if __name__ == "__main__":
    main()
